import url from "@/utils/common";

const pokerMap = [
    {"id":0, "value":1, "type": 0  ,"tag":'1'},
    {"id":1, "value":1, "type": 1  ,"tag":'1'},
    {"id":2, "value":1, "type": 2  ,"tag":'1'},
    {"id":3, "value":1, "type": 3  ,"tag":'1'},
    {"id":4, "value":2, "type": 0  ,"tag":'2'},
    {"id":5, "value":2, "type": 1  ,"tag":'2'},
    {"id":6, "value":2, "type": 2  ,"tag":'2'},
    {"id":7, "value":2, "type": 3  ,"tag":'2'},
    {"id":8, "value":3, "type": 0  ,"tag":'3'},
    {"id":9, "value":3, "type": 1  ,"tag":'3'},
    {"id":10, "value":3, "type": 2 ,"tag":'3'},
    {"id":11, "value":3, "type": 3 ,"tag":'3'},
    {"id":12, "value":4, "type": 0 ,"tag":'4'},
    {"id":13, "value":4, "type": 1 ,"tag":'4'},
    {"id":14, "value":4, "type": 2 ,"tag":'4'},
    {"id":15, "value":4, "type": 3 ,"tag":'4'},
    {"id":16, "value":5, "type": 0 ,"tag":'5'},
    {"id":17, "value":5, "type": 1 ,"tag":'5'},
    {"id":18, "value":5, "type": 2 ,"tag":'5'},
    {"id":19, "value":5, "type": 3 ,"tag":'5'},
    {"id":20, "value":6, "type": 0 ,"tag":'6'},
    {"id":21, "value":6, "type": 1 ,"tag":'6'},
    {"id":22, "value":6, "type": 2 ,"tag":'6'},
    {"id":23, "value":6, "type": 3 ,"tag":'6'},
    {"id":24, "value":7, "type": 0 ,"tag":'7'},
    {"id":25, "value":7, "type": 1 ,"tag":'7'},
    {"id":26, "value":7, "type": 2 ,"tag":'7'},
    {"id":27, "value":7, "type": 3 ,"tag":'7'},
    {"id":28, "value":8, "type": 0 ,"tag":'8'},
    {"id":29, "value":8, "type": 1 ,"tag":'8'},
    {"id":30, "value":8, "type": 2 ,"tag":'8'},
    {"id":31, "value":8, "type": 3 ,"tag":'8'},
    {"id":32, "value":9, "type": 0 ,"tag":'9'},
    {"id":33, "value":9, "type": 1 ,"tag":'9'},
    {"id":34, "value":9, "type": 2 ,"tag":'9'},
    {"id":35, "value":9, "type": 3 ,"tag":'9'},
    {"id":36, "value":10, "type": 0,"tag":'0'},
    {"id":37, "value":10, "type": 1,"tag":'0'},
    {"id":38, "value":10, "type": 2,"tag":'0'},
    {"id":39, "value":10, "type": 3,"tag":'0'},
    {"id":40, "value":11, "type": 0,"tag":'j'},
    {"id":41, "value":11, "type": 1,"tag":'j'},
    {"id":42, "value":11, "type": 2,"tag":'j'},
    {"id":43, "value":11, "type": 3,"tag":'j'},
    {"id":44, "value":12, "type": 0,"tag":'q'},
    {"id":45, "value":12, "type": 1,"tag":'q'},
    {"id":46, "value":12, "type": 2,"tag":'q'},
    {"id":47, "value":12, "type": 3,"tag":'q'},
    {"id":48, "value":13, "type": 0,"tag":'k'},
    {"id":49, "value":13, "type": 1,"tag":'k'},
    {"id":50, "value":13, "type": 2,"tag":'k'},
    {"id":51, "value":13, "type": 3,"tag":'k'},
    {"id":52, "value":14, "type": 4,"tag":'s'},
    {"id":53, "value":15, "type": 5,"tag":'S'},
]

export default pokerMap